FROM python:3.12.1-bullseye

# Install npm
RUN apt-get update && apt-get -y upgrade && \
    apt-get install -y --no-install-recommends \
    npm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g n
RUN n stable

# Set the working directory in the container
WORKDIR /app

COPY . /app
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# CMD [ "python", "./main.py" ]
ENTRYPOINT ["tail", "-f", "/dev/null"]